name: OpenAPI spec published
on:
  push:
    branches: [main]
    paths:
      - 'spec/openapi.yml'
  workflow_dispatch:
jobs:
  publish-openapi-spec:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Swagger UI
        uses: Legion2/swagger-ui-action@v1
        with:
          output: docs
          spec-file: openapi.json
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs
