name: OpenAPI spec current
on:
  push:
    branches: [main]
    paths:
      - 'spec/openapi.yml'
  workflow_dispatch:
jobs:
  update-openapi-ui:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Ensure docs path exists
        run: mkdir -p docs
      - name: Generate Swagger UI
        uses: Legion2/swagger-ui-action@v1
        with:
          output: docs
          spec-file: spec/openapi.yml
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Zachary Proser
          author_email: zackproser@gmail.com
          message: 'Update OpenAPI spec'
          add: 'docs'
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs
