name: Pulumi
on:
  - pull_request
env:
  PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v3.5.0
        with:
          node-version: '18'
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Install dependencies
        run: |
          npm install
      - name: Ensure pulumi has correct stack selected
        run: pulumi stack select pageripper-dev
      - name: Ensure Pulumi config has correct AWS region set
        run: pulumi config set aws:region ${{ secrets.AWS_REGION }}
      - name: Run Pulumi preview
        uses: pulumi/actions@v3
        with:
          command: preview
          stack-name: pageripper-dev
