name: OpenAPI spec valid
on:
  push:
    branches: [main]
    paths:
      - 'spec/openapi.yml'
  workflow_dispatch:
jobs:
  update-openapi-ui:
    container: gkarthics/swagger-validate:0.2.0
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: validate
        run: validate spec
